---
- name: Install Fatpak packages
  hosts: localhost

  vars_files:
    - _vars_base.yml
    - '{{ repo_root_path }}/default.pkgs.yml'

  pre_tasks:
    - name: Prepare steps
      block:
        - name: Install flatpak
          include_tasks: '{{ ansible_path }}/_install_flatpak.yml'

        - name: Get window system protocol and DE name
          set_fact:
            wsp_name: '{{ ansible_facts.env.XDG_SESSION_TYPE }}'
            de_name: '{{ ansible_facts.env.XDG_CURRENT_DESKTOP | lower }}'

        - name: Include pkgs list
          include_vars: '{{ item }}'
          with_fileglob:
            - '{{ repo_root_path }}/pkgs.yml'
      tags: prepare

  tasks:
    - name: Base pkgs
      block:
        - name: Flatseal
          block:
            - name: Install Flatseal
              flatpak:
                name: com.github.tchx84.Flatseal
                state: present

        - name: Extension Manager
          block:
            - name: Install Extension Manager
              flatpak:
                name: com.mattjakeman.ExtensionManager
                state: present
            - name: Configure Extension Manager
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=ipc \
                    --nosocket=x11 \
                    com.mattjakeman.ExtensionManager
              when: wsp_name=="wayland"
          when: de_name=="gnome"

        - name: Mission Center
          block:
            - name: Install Mission Center
              flatpak:
                name: io.missioncenter.MissionCenter
                state: present
          when: de_name=="gnome"

      tags: base_flatpak_pkgs

    - name: Install Flatpak PKGs from list
      flatpak:
        name: '{{ flatpak_pkgs }}'
        state: present
      when:
        - flatpak_pkgs is defined
        - flatpak_pkgs | length > 0
      tags: other_flatpak_pkgs

    - name: Override flatpak PKGs settings
      block:
        # Amberol
        - name: Amberol
          block:
            - name: Configure Amberol permissions [Wayland]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=network \
                    --unshare=ipc \
                    --nosocket=x11 \
                    --nosocket=fallback-x11 \
                    io.bassi.Amberol
              when: wsp_name=="wayland"
            - name: Configure Amberol permissions [X11]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=network \
                    --nosocket=wayland \
                    io.bassi.Amberol
              when: wsp_name=="x11"
          when: "'io.bassi.Amberol' in flatpak_pkgs"

        # Rhythmbox
        - name: Rhythmbox
          block:
            - name: Configure Rhythmbox permissions [Wayland]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=network \
                    --unshare=ipc \
                    --nosocket=x11 \
                    --nosocket=fallback-x11 \
                    org.gnome.Rhythmbox
              when: wsp_name=="wayland"
            - name: Configure Rhythmbox permissions [X11]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=network \
                    --nosocket=wayland \
                    org.gnome.Rhythmbox
              when: wsp_name=="x11"
          when: "'org.gnome.Rhythmbox3' in flatpak_pkgs"

        # Loupe
        - name: Loupe
          block:
            - name: Configure Loupe permissions [Wayland]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=ipc \
                    --nosocket=x11 \
                    --nosocket=fallback-x11 \
                    org.gnome.Loupe
              when: wsp_name=="wayland"
            - name: Configure Loupe permissions [X11]
              shell:
                cmd: >
                  flatpak override --user \
                    --nosocket=wayland \
                    org.gnome.Loupe
              when: wsp_name=="x11"
          when: "'org.gnome.Loupe' in flatpak_pkgs"

        # Celluloid
        - name: Celluloid
          block:
            - name: Configure Celluloid permissions [Wayland]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=network \
                    --unshare=ipc \
                    --nosocket=x11 \
                    --nosocket=fallback-x11 \
                    --nodevice=all \
                    --device=dri \
                    io.github.celluloid_player.Celluloid
              when: wsp_name=="wayland"
            - name: Configure Celluloid permissions [X11]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=network \
                    --nosocket=wayland \
                    --nodevice=all \
                    --device=dri \
                    io.github.celluloid_player.Celluloid
              when: wsp_name=="x11"
          when: "'io.github.celluloid_player.Celluloid' in flatpak_pkgs"

        # Brave
        - name: Brave
          block:
            - name: Configure Brave permissions [Wayland]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=ipc \
                    --nosocket=pcsc \
                    --nofilesystem=host-etc \
                    --nofilesystem=xdg-desktop \
                    --nofilesystem=xdg-documents \
                    --nofilesystem=xdg-videos \
                    --nofilesystem=xdg-music \
                    com.brave.Browser
              when: wsp_name=="wayland"
            - name: Configure Brave permissions [X11]
              shell:
                cmd: >
                  flatpak override --user \
                    --nosocket=wayland \
                    --nosocket=pcsc \
                    --nofilesystem=host-etc \
                    --nofilesystem=xdg-desktop \
                    --nofilesystem=xdg-documents \
                    --nofilesystem=xdg-videos \
                    --nofilesystem=xdg-music \
                    com.brave.Browser
              when: wsp_name=="x11"
          when: "'com.brave.Browser' in flatpak_pkgs"

        # Librewolf
        - name: Librewolf
          block:
            - name: Configure Librewolf permissions [Wayland]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=ipc \
                    --nosocket=x11 \
                    --nosocket=fallback-x11 \
                    --nosocket=pcsc \
                    io.gitlab.librewolf-community
              when: wsp_name=="wayland"
            - name: Configure Librewolf permissions [X11]
              shell:
                cmd: >
                  flatpak override --user \
                    --nosocket=wayland \
                    --nosocket=pcsc \
                    io.gitlab.librewolf-community
              when: wsp_name=="x11"
          when: "'io.gitlab.librewolf-community' in flatpak_pkgs"

        # Bitwarden
        - name: Bitwarden
          block:
            - name: Configure Bitwarden permissions [Wayland]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=ipc \
                    --nodevice=all \
                    --nofilesystem=xdg-config/microsoft-edge/NativeMessagingHosts \
                    --nofilesystem=~/.var/app/org.mozilla.firefox/.mozilla \
                    --nofilesystem=xdg-config/google-chrome/NativeMessagingHosts \
                    --nofilesystem=xdg-download \
                    --nofilesystem=~/.var/app/org.chromium.Chromium/config/chromium/NativeMessagingHosts \
                    --nofilesystem=~/.var/app/com.microsoft.Edge/config/microsoft-edge/NativeMessagingHosts \
                    --nofilesystem=xdg-config/chromium/NativeMessagingHosts \
                    --nofilesystem=~/.var/app/com.google.Chrome/config/google-chrome/NativeMessagingHosts \
                    com.bitwarden.desktop
              when: wsp_name=="wayland"
            - name: Configure Bitwarden permissions [X11]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=ipc \
                    --nosocket=wayland \
                    --nodevice=all \
                    --nofilesystem=xdg-config/microsoft-edge/NativeMessagingHosts \
                    --nofilesystem=~/.var/app/org.mozilla.firefox/.mozilla \
                    --nofilesystem=xdg-config/google-chrome/NativeMessagingHosts \
                    --nofilesystem=xdg-download \
                    --nofilesystem=~/.var/app/org.chromium.Chromium/config/chromium/NativeMessagingHosts \
                    --nofilesystem=~/.var/app/com.microsoft.Edge/config/microsoft-edge/NativeMessagingHosts \
                    --nofilesystem=xdg-config/chromium/NativeMessagingHosts \
                    --nofilesystem=~/.var/app/com.google.Chrome/config/google-chrome/NativeMessagingHosts \
                    com.bitwarden.desktop
              when: wsp_name=="x11"
          when: "'com.bitwarden.desktop' in flatpak_pkgs"

        # Telegram
        - name: Telegram
          block:
            - name: Configure Telegram permissions [Wayland]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=ipc \
                    --nosocket=x11 \
                    --nofilesystem=host \
                    --filesystem=xdg-download \
                    org.telegram.desktop
              when: wsp_name=="wayland"
            - name: Configure Telegram permissions [X11]
              shell:
                cmd: >
                  flatpak override --user \
                    --nosocket=wayland \
                    --nofilesystem=host \
                    --filesystem=xdg-download \
                    --env=IBUS_USE_PORTAL=1 \
                    org.telegram.desktop
              when: wsp_name=="x11"
          when: "'org.telegram.desktop' in flatpak_pkgs"

        # Spotify
        - name: Spotify
          block:
            - name: Configure Spotify permissions [Wayland]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=ipc \
                    --nofilesystem=xdg-pictures \
                    com.spotify.Client
              when: wsp_name=="wayland"
            - name: Configure Spotify permissions [X11]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=ipc \
                    --nosocket=wayland \
                    --nofilesystem=xdg-pictures \
                    com.spotify.Client
              when: wsp_name=="x11"
          when: "'com.spotify.Client' in flatpak_pkgs"

        # FreeTube
        - name: FreeTube
          block:
            - name: Configure FreeTube permissions [Wayland]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=ipc \
                    --nosocket=x11 \
                    --nosocket=fallback-x11 \
                    io.freetubeapp.FreeTube
              when: wsp_name=="wayland"
            - name: Configure FreeTube permissions [X11]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=ipc \
                    --nosocket=wayland \
                    io.freetubeapp.FreeTube
              when: wsp_name=="x11"
          when: "'io.freetubeapp.FreeTube' in flatpak_pkgs"

        # LibreOffice
        - name: LibreOffice
          block:
            - name: Configure LibreOffice permissions [Wayland]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=network \
                    --unshare=ipc \
                    --nosocket=x11 \
                    --nosocket=fallback-x11 \
                    --nosocket=pulseaudio \
                    --socket=cups \
                    --nofilesystem=host \
                    --filesystem=home \
                    org.libreoffice.LibreOffice
              when: wsp_name=="wayland"
            - name: Configure LibreOffice permissions [X11]
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=network \
                    --nosocket=wayland \
                    --nosocket=pulseaudio \
                    --socket=cups \
                    --nofilesystem=host \
                    --filesystem=home \
                    org.libreoffice.LibreOffice
              when: wsp_name=="x11"
          when: "'org.libreoffice.LibreOffice' in flatpak_pkgs"

        # OnlyOffice
        - name: OnlyOffice
          block:
            - name: Configure OnlyOffice permissions
              shell:
                cmd: >
                  flatpak override --user \
                    --unshare=network \
                    --nosocket=pulseaudio \
                    --socket=cups \
                    org.onlyoffice.desktopeditors
          when: "'org.onlyoffice.desktopeditors' in flatpak_pkgs"
      tags: other_flatpak_pkgs
